# Generated by Django 5.2.2 on 2025-06-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('servico', models.CharField(choices=[('landing page', 'Landing page'), ('site institucional', 'Site institucional'), ('site estatico', 'Site estático'), ('outro', 'Outro')], max_length=18, verbose_name='Escolher serviço')),
                ('decricao', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
