# Generated by Django 5.2.2 on 2025-06-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='decricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='servico',
            new_name='tp_servico',
        ),
    ]
