# Generated by Django 5.2.2 on 2025-06-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_decricao_cliente_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tp_servico',
            field=models.CharField(choices=[('landing page', 'Landing page'), ('site institucional', 'Site institucional'), ('site estatico', 'Site estático'), ('outro', 'Outro')], max_length=18, verbose_name='tipo de servico'),
        ),
    ]
